### ISSUE TITLE
How to uninstall PX4 Windows Toolchain 

### ISSUE THREAD

**Issue by mengchaoheng** [MaEtUgR/PX4Toolchain#27]
I want to install the old version of PX4.Windows.Cygwin.Toolchain.0.8, but it says that the new version has been installed. How do I uninstall the new version?

![image](https://user-images.githubusercontent.com/43166007/115175763-3702cd80-a0fe-11eb-97e6-0291653d5133.png)

**Comment by mengchaoheng** [comment]
I want to use the PSP Toolbox ，as in the https://uk.mathworks.com/help/supportpkg/px4/ug/setup-cygwin-toolchain.html, so I need  V0.8

**Comment by hamishwillee** [comment]
@mengchaoheng You uninstall in the same way as any other windows program - start bar > Add or remove programs . Then select PX4 toolchain from the list.
