### ISSUE TITLE
make px4_sitl jmavsim failed

### ISSUE THREAD

**Issue by scps990210** [MaEtUgR/PX4Toolchain#36]
Excuse me, i installed px4 by Amazon S3 and do the instructs in [this](https://dev.px4.io/v1.11_noredirect/en/setup/dev_env_windows_cygwin.html#getting_started) step by step. But when i do the command make px4_sitl jmavsim it encountered some problems below 
![image](https://user-images.githubusercontent.com/66359433/190842722-af5368d4-4b63-4d87-8a99-af66ce2587ce.png)

**Comment by hamishwillee** [comment]
That should work if you are targeting PX4 v1.11; perhaps @MaEtUgR can comment.

If it was me I would use WSL2 - following the instructions in http://docs.px4.io/main/en/dev_setup/dev_env_windows_wsl.html but using the PX4 v1.11 sources.

**Comment by scps990210** [comment]
Thanks for your reply! I have followed the steps in http://docs.px4.io/main/en/dev_setup/dev_env_windows_wsl.html to install wsl2 but when i type "make px4_sitl " it show "ninja: no work to do.".
and when i type "make px4_sitl jmavsim" it still encounter some problems below 
![image](https://user-images.githubusercontent.com/66359433/190949094-5dbb5aa2-c5db-48cf-8d36-a03b0e45035b.png)
i think i have problems about how to set the version to 1.11 while doing the work in http://docs.px4.io/main/en/dev_setup/dev_env_windows_wsl.html

**Comment by hamishwillee** [comment]
Any reason why you have to stay at PX4 v1.11? I'll try look at this on Wednesday.

**Comment by scps990210** [comment]
OK, thank you! 
Because you suggest me to follow the instructions in http://docs.px4.io/main/en/dev_setup/dev_env_windows_wsl.html but using the PX4 v1.11 sources. But i don't know how to use the wsl with PX4 v1.11 sources.

**Comment by Quietly-20201113** [comment]
I built it in window11 and followed the tutorial in 
[Windows Cygwin 工具链](https://dev.px4.io/v1.11_noredirect/zh/setup/dev_env_windows_cygwin.html), but I received the following error message. I can't upgrade cmake anyway. Please tell me. What should be done
```html
-- stdout output is:
loading initial cache file /cygdrive/c/PX4/home/Firmware/build/px4_sitl_default/src/modules/uxrce_dds_client/tmp/libmicroxrceddsclient_project-cache-RelWithDebInfo.cmake
-- Configuring incomplete, errors occurred!

-- stderr output is:
CMake Error at CMakeLists.txt:18 (cmake_minimum_required):
  CMake 3.16 or higher is required.  You are running version 3.14.5



CMake Error at /cygdrive/c/PX4/home/Firmware/build/px4_sitl_default/src/modules/uxrce_dds_client/src/libmicroxrceddsclient_project-stamp/libmicroxrceddsclient_project-configure-RelWithDebInfo.cmake:47 (message):
  Stopping after outputting logs.


[19/235] Building CXX object src/systemcmds/tests/CMakeFiles/systemcmds__tests.dir/test_matrix.cpp.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:232：px4_sitl] 错误 1
```

**Comment by hamishwillee** [comment]
We're up to PX4 v1.14 - I suggest you migrate up from PX4 v1.11 and you're more likely to get support. 

If I had to get this working I would TRY to do this on WSL2 - so follow the WSL2 setup instructions from https://docs.px4.io/main/en/dev_setup/dev_env_windows_wsl.html#overview BUT install Ubuntu 20.04 rather than 20.02

Then use https://github.com/PX4/PX4-Autopilot/blob/v1.11.0/Tools/setup/ubuntu.sh as per the instructions to install the development environment.

And fetch PX4 v1.11 release branch and build that. 

Note also that I would try Gazebo rather than jmavsim, which is now "community supported">

I'm closing this, as the Cygwin windows toolchain is no longer supported.
